### ISSUE TITLE
Reduce doesn't work.

### ISSUE THREAD

**Issue by kunkun-tang** [mw-ding/MapReduceFramework#1]
Hi, I'm interested in your implementation of Map-Reduce, and getting into it. I'm trying to run word-count example. Mapper works, since it already printed intermediate map result in /tmp folder. 

Based on the console log, I found this framework launched mapper and reduce at the same time? Therefore, should reduce phase read result from /tmp folder perieodically?  In my machine, reducers keeps printing INPROGRESS. 

Therefore, is it a bug or something?

I will keep deeping into ur implementation. If it has any bug, I will point it out. 
Thanks

**Comment by mw-ding** [comment]
Hi, Thanks for filing this issue. Well, I have to say that I haven't maintain this project for a while. And yes, there might be some bugs for now.

Recently, I am trying to improve the code a bit and make it easier to be deployed.

By the way, would you mind sharing the exact exception messages that you got? I am guessing that there might be something wrong with the JAVA-RMI

**Comment by kunkun-tang** [comment]
Thanks for your reply. 
I checked reduceerr just now.

it said:
java.lang.NumberFormatException: For input string: "3.We"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:441)
        at java.lang.Long.parseLong(Long.java:483)
        at example.wordcount.WCReducer.reduce(WCReducer.java:15)
        at mapreduce.ReducerWorker.run(ReducerWorker.java:282)
        at mapreduce.ReducerWorker.main(ReducerWorker.java:338)

**Comment by kunkun-tang** [comment]
RMI also confused me a while. The port in makefile doesn't match 1234 in config.

Another problem is in Utility class.

private static String MAPREDUCE_HOME = System.getenv().get("MAPREDUCE_HOME");
U didn't tell the reader to set this environment variable.

Anyhow, your implementation was elegant enough, since you commented everywhere, It is really good enough for me to get into the basics of hadoop implementation. Appreciate.

**Comment by mw-ding** [comment]
Well, I will take a look at these problems later. Currently I am working on code refactoring. Before this, please do not fetch or pull from the repository.

Also, please use 'git checkout tag/v0.1' to go the the first cut of our implementation.

**Comment by kunkun-tang** [comment]
Hi mw,

I changed the input file, which only contains string and space. The replaced one worked very good. So the problem might come from parsing input file. It seems that if the input file has '\t' before a string, bug happens.

**Comment by mw-ding** [comment]
Yeah, we only provide the minimum error handling. Sorry for that. 

Anyway, it's good to know that you successfully make it run.
